name: chromosearch
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython=1.84
  - blast=2.16.0
  - matplotlib=3.9.2
  - numpy=2.1.0
  - python=3.12.5
  - pandas=2.2.2
  - prodigal=2.6.3
  - scipy=1.14.1
  - seaborn=0.13.2
  - statsmodels=0.14.2

